### ISSUE TITLE
Corrections wording sur la page d'accueil

### ISSUE THREAD

**Issue by juliendelrio** [GDGToulouse/site-devfest-toulouse-2016#2]
Quelques corrections à faire sur la page d'accueil :
- Trait d'union à Peut être
- "la soirée" devient "l'afterwork"
- "amphis" devient "Amphithéâtres"
- changer "devfest-toulouse-team@googlegroups.com" par "devfest@toulouseaug.fr"

**Comment by vferries** [comment]
Je suis pas fan de "afterwork" mais open pour en discuter. On aura pas vraiment bossé là pour le coup.
J'ai corrigé le reste mais ne pourrai relivrer sur firebase qu'au retour (avec la fibre ça ira mieux)
